### ISSUE TITLE
Module can be cloned on the same module

### ISSUE THREAD

**Issue by OskarMorel** [Rocket-CDS/DNNrocket#77]
Possibility of cloning a module on the same module. 

---

If you follow the basic procedure, everything will be fine and the page selected at the beginning will be unavailable.

![image](https://github.com/Rocket-CDS/DNNrocket/assets/103489695/99b40c5c-a141-4b74-a515-336915808179)

But if, after completing the basic procedure, you change pages without clicking, and therefore modules without clicking the next button, you'll have access to the same page.

![image](https://github.com/Rocket-CDS/DNNrocket/assets/103489695/771d9bde-6fe7-41f4-9e74-7462530f8ff2)

**Comment by leedavi** [comment]
Again more explanation.

**Comment by leedavi** [comment]
Disable the dropdown for pages after first selection.  If the user needs another selection they need to use the refresh button.
