### ISSUE TITLE
Roles are saved in dnn but not in RocketTools

### ISSUE THREAD

**Issue by OskarMorel** [Rocket-CDS/DNNrocket#78]
After adding roles to modules, everything works. Modules can be modified by the selected roles. But on Rocket Tools Roles, you can't see that this module has been assigned roles. 

---

Before registration (while selecting roles and modules)

![image](https://github.com/Rocket-CDS/DNNrocket/assets/103489695/d3c5f6ed-d5d3-4c50-928f-6fb3bca09d1c)

After registration (you can see that nothing has been registered)

![image](https://github.com/Rocket-CDS/DNNrocket/assets/103489695/41e1fc2e-22cf-43e8-983a-b98c2b6fc69b)

**Comment by leedavi** [comment]
This seems odd, but is correct.  The idea is to add the roles in DNN.  It does not show on this screen because you can have multiple modules, all which can have different roles.  So that cannot be shown.  Only the default "Manager" role is preselected to save time.
