### ISSUE TITLE
RocketTool PL - Adds a dot to empty fields when saving

### ISSUE THREAD

**Issue by OskarMorel** [Rocket-CDS/DNNrocket#79]
When saving, add a dot in the empty fields. Add dots also in DNN pages

--- 

**Before Saving**

![image](https://github.com/Rocket-CDS/DNNrocket/assets/103489695/9da0eabc-dc04-4599-a6ce-708e334e7f44)

**After Saving**

![image](https://github.com/Rocket-CDS/DNNrocket/assets/103489695/8ba68006-0e65-4216-8c13-05f679b5c25a)

**Comment by leedavi** [comment]
Again more explanation.  Pretend you have not demoed it to me.  Although I do remember this one.
