### ISSUE TITLE
RocketTools PL - Change window size when delete a link or validating a parameter

### ISSUE THREAD

**Issue by OskarMorel** [Rocket-CDS/DNNrocket#80]
When deleting a link or saving a parameter change. RocketTools PL changes size

**Comment by leedavi** [comment]
You need to explain more... should some screen shots or something else.  The idea is the issue report should save time what trying to find or identify a problem.

**Comment by OskarMorel** [comment]
At the start of Rocket Tools PageLocalization
![image](https://github.com/Rocket-CDS/DNNrocket/assets/103489695/3ac60def-2d98-4cd8-abad-e4e77ba89fc0)

---

After you validated settings in Page Localization 

![image](https://github.com/Rocket-CDS/DNNrocket/assets/103489695/8ddb6059-0b13-400e-a872-f48868496fed)

**Comment by OskarMorel** [comment]
Do the same when you delete an URL

![image](https://github.com/Rocket-CDS/DNNrocket/assets/103489695/1425966f-c0ab-47bc-bfae-771a24c18cf4)
